package xml;

import java.io.File;
import java.io.IOException;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.FactoryConfigurationError;
import javax.xml.parsers.ParserConfigurationException;
import org.w3c.dom.Node;

import org.xml.sax.SAXException;
import org.xml.sax.SAXParseException;

import org.w3c.dom.Document;
import org.w3c.dom.NodeList;
import org.w3c.dom.DOMException;

public class DomExample {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();

		try {
			File xmlFile = new File("D:/ws/git/java/Core/src/xml/Employee.xml");
			DocumentBuilder builder = factory.newDocumentBuilder();
			Document document = builder.parse(xmlFile);
			System.out.println(document.getFirstChild());
			NodeList nodeList = document.getElementsByTagName("name");
			System.out.println("nodeList.getLength(): "+nodeList.getLength());
			for(int i=0;i<nodeList.getLength();i++){
				Node node=(Node)nodeList.item(i);
				System.out.println("Node Name: "+node.getNodeName());
				NodeList childOfNode=node.getChildNodes();
				System.out.println("childOfNode.getLength(): "+childOfNode.getLength());
				for(int j=0;j<childOfNode.getLength();j++){
					Node childNode=(Node)childOfNode.item(i);
					System.out.println("Child Node Name: "+childNode.getNodeName());
					System.out.println("Child Node Value: "+childNode.getNodeValue());
				}
				
			}
		} catch (SAXParseException spe) {
			// Error generated by the parser
			System.out.println("\n** Parsing error" + ", line " + spe.getLineNumber() + ", uri " + spe.getSystemId());
			System.out.println("  " + spe.getMessage());

			// Use the contained exception, if any
			Exception x = spe;
			if (spe.getException() != null)
				x = spe.getException();
			x.printStackTrace();
		} catch (SAXException sxe) {
			// Error generated by this application
			// (or a parser-initialization error)
			Exception x = sxe;
			if (sxe.getException() != null)
				x = sxe.getException();
			x.printStackTrace();
		} catch (ParserConfigurationException pce) {
			// Parser with specified options
			// cannot be built
			pce.printStackTrace();
		} catch (IOException ioe) {
			// I/O error
			ioe.printStackTrace();
		}
	}
}
