server:
  port: 9443
  ssl:
    key-alias: sciresp1k
    key-password: p1kscires
# Place the jks under resources folder
    key-store: classpath:scires.jks
    key-store-provider: SUN
    key-store-type: JKS

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

facebook:
  client:
    clientId: 1092168480922342
    clientSecret: 6faa615b2705d8ddb80a26e156d16687
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
logging:
  level:
    org.springframework.security: DEBUG
